services:
  selenium-hub:
    image: seleniarm/hub:latest  # Use latest version instead of 4.13.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"  # Event bus publish
      - "4443:4443"  # Event bus subscribe
    environment:
      - SE_NODE_MAX_SESSIONS=5  # Allow up to 5 concurrent sessions

  chrome:
    image: seleniarm/node-chromium:latest  # Use latest ARM-compatible Chrome node
    platform: linux/arm64
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSION=1  # One session per node to prevent overload
    shm_size: "2g"

  firefox:
    image: seleniarm/node-firefox:latest  # Use latest ARM-compatible Firefox node
    platform: linux/arm64
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSION=1  # One session per node to prevent overload
    volumes:
      - /Users/pravinmistry/Library/Application Support/Firefox/Profiles/7s2j4yfa.default-release-1737955747675:/home/seluser/.mozilla/firefox/myprofile
      - /Users/pravinmistry/Library/Application Support/Firefox/profiles.ini:/home/seluser/.mozilla/firefox/profiles.ini
    shm_size: "2g"