name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: macos-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:latest
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Chrome & ChromeDriver (macOS)
        run: |
          brew install google-chrome
          brew install chromedriver

      - name: Kill Any Running Chrome Processes
        run: |
          pkill -9 chrome || true
          pkill -9 chromedriver || true

      - name: Wait for Selenium Grid to be ready
        run: |
          for i in {1..30}; do
            if curl -sSL "http://localhost:4444/status" | grep -q '"ready":true'; then
              echo "Selenium Grid is ready!";
              break;
            fi
            echo "Waiting for Selenium Grid...";
            sleep 5;
          done

      - name: Run Tests
        run: mvn clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/testng-results.xml
