name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Chrome & ChromeDriver (macOS)
        run: |
          brew install google-chrome
          brew install chromedriver

      - name: Kill Any Running Chrome Processes
        run: |
          pkill -9 chrome || true
          pkill -9 chromedriver || true

      - name: Run Tests
        run: mvn clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/testng-results.xml
